config/routes.rb
Rails.application.routes.draw do

  resources :interns do
    get :shuffled, on: :collection
  end

  root to: 'interns#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/intern.rb
class Intern < ApplicationRecord
  validates_presence_of :first_name, :last_name
  validates :first_name, :last_name, length:{ minimum:3}
  validates :last_name, :uniqueness => { :scope => :first_name }

  def self.random_pairs!
    interns = all.to_a.shuffle
    raise ArgumentError.new('Oops error..') unless interns.size % 2 == 0
    return interns.each_slice(2).to_a
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: ENV['LOGIN'], password: ENV['PASSWORD']
  protect_from_forgery with: :exception
end

app/controllers/interns_controller.rb
class InternsController < ApplicationController
    before_action :set_intern, only: [:show, :edit, :update, :destroy]

    def index
      @interns = Intern.all
    end

    def shuffled
      @interns = Intern.random_pairs!
      rescue ArgumentError
        flash[:alert] = t('interns.cant_generate')
        redirect_to action: :new
    end

    def new
      @intern = Intern.new
    end

    def create
      @intern = Intern.new(intern_params)
      if @intern.save
        flash[:notice] = t('interns.created')
        redirect_to action: :index
      else
        render :new
      end
    end

    def update
        if @intern.update(intern_params)
          flash[:notice] = t('interns.updated')
          redirect_to action: :index
        else
          render :edit
        end
    end

    def destroy
      @intern.destroy
        flash[:notice] = t('interns.destroyed')
        redirect_to action: :index
    end

    private
      def set_intern
        @intern = Intern.find(params[:id])
      end

      def intern_params
        params.require(:intern).permit(:first_name, :last_name)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper

  # flash_styleclass(:notice)
  # flash_styleclass[:notice]
  # flash_styleclass(:info)
  # flash_styleclass[:info]
  def flash_styleclass(key=nil)
    default_keys = ({
      notice: 'info',
      alert: 'warning'
    }).with_indifferent_access

    key ? default_keys[key] : ->(k) { default_keys[k] || k }
  end

  def flash_button_tag
    content_tag(:button, '&times;'.html_safe, class: 'close', type: 'button', 'aria-hidden' => 'true', data: { dismiss: 'alert' })
  end

end

app/helpers/interns_helper.rb
module InternsHelper
  def formatted_pairs()
    @interns
  end
end

app/views/interns/_form.html.haml
= simple_form_for @intern do |f|
  - if intern.errors.any?
    #error_explanation
      %h2
        = pluralize(intern.errors.count, "error")
        prohibited this intern from being saved:
      %ul
        - intern.errors.full_messages.each do |message|
          %li= message

  = f.input :first_name

  = f.input :last_name

  = f.button :submit

app/views/interns/edit.html.haml
%h1 Editing Intern
= render 'form', intern: @intern
%br/
= link_to t('shared.show'), @intern, :class => 'btn btn-sm btn-info'
= link_to t('shared.back'), interns_path,:class => 'btn btn-sm btn-info'

app/views/interns/index.html.haml
%h3 Interns
.col-md-12
  %table.table.table-striped.table-responsive
    %thead
      %tr
        %th First name
        %th Last name
        %th{:colspan => "5"}
    %tbody
      - @interns.each do |intern|
        %tr
          %td
            %p= intern.first_name
          %td
            %p= intern.last_name
          %td= link_to t('shared.show'), intern, :class => 'btn btn-sm btn-primary'
          %td= link_to t('shared.edit'), edit_intern_path(intern) , :class => 'btn btn-sm btn-info'
          %td= link_to t('shared.delete'), intern, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-sm btn-danger'
%br/
= link_to t('shared.new_intern'), new_intern_path , :class => 'btn btn-sm btn-danger'
%br/
%br/
= link_to t('shared.shuffled'), shuffled_interns_path, :class => 'btn btn-sm btn-primary'

app/views/interns/new.html.haml
%h1 New Intern
= render 'form', intern: @intern
%br/
= link_to t('shared.back'), interns_path ,:class => 'btn btn-sm btn-info'

app/views/interns/show.html.haml
%p#notice= notice
%p
  %strong First name:
  = @intern.first_name
%p
  %strong Last name:
  = @intern.last_name
= link_to t('shared.edit'), edit_intern_path(@intern) ,:class => 'btn btn-sm btn-info'
|
= link_to t('shared.back'), interns_path ,:class => 'btn btn-sm btn-info'

app/views/interns/shuffled.html.haml
%h3 Shuffled Interns
.row
  .col-md-12
    %table.table.table-striped.table-responsive
      %thead
        %tr
          %th Number
          %th First Intern
          %th Second Intern
      %tbody
        - @interns.each_with_index do |interns_pair,index|
          %tr
            %td
              %p= 'Pair #' + (index+1).to_s
            - interns_pair.each do |intern|
              %td.intern
                %p= intern.first_name
                %p= intern.last_name
%br/
= link_to t('shared.repeat'), shuffled_interns_path , data: {turbolinks: false}, :class => 'btn btn-sm btn-primary'
%br/
%br/
= link_to t('shared.back'), interns_path , :class => 'btn btn-sm btn-primary'

app/views/layouts/_flash.html.haml
- flash.each do |key, msg|
  .alert{ class: "alert-#{flash_styleclass[key]}", role: 'alert' }
    .container.container-center
      = flash_button_tag
      = msg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pairs
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Indie+Flower", :rel => "stylesheet"}/
  %body
    = render 'layouts/flash'
    = yield